---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, plone, --force-alphabetical-sort, --force-single-line, --lines-after-imports, "2"]
        additional_dependencies: [setuptools]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        name: doc8
        description: This hook runs doc8 for linting docs.
        entry: python -m doc8
        language: python
        files: \.rst$
        require_serial: true
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.7.9
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-docstrings
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.2.4
  #   hooks:
  #   - id: python-safety-dependencies-check