[tox]
envlist =
    lint
    py37
    py38
    py39
    py310
    py311
minversion = 3.25.0
requires =
    virtualenv >= 20.14.1
    pip >= 22.1.2
isolated_build = True

[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310, lint
    3.11: py311

[testenv]
extras = test
setenv =
    PYTHONHASHSEED = 0
commands = python -m pytest {posargs}

[testenv:py37]
extras = test
setenv =
    PYTHONHASHSEED = 0
commands = python -m coverage run -m pytest {posargs}

[testenv:py310]
extras = test
setenv =
    PYTHONHASHSEED = 0
commands = python -m coverage run -m pytest {posargs}

[testenv:lint]
commands =
    python -m pre_commit run {posargs:--all}
deps = pre-commit>=1.20.0
usedevelop = false

[testenv:coverage-report]
basepython = python3.10
deps = coverage[toml]
skip_install = true
parallel_show_output = true
depends = py37,py310
commands =
    python -m coverage combine
    python -m coverage report
