name: Testing

on:
  push:
  pull_request:
   types:
     - "reopened"
     - "opened"
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run lint with tox
        run: uvx --with tox-uv tox -e lint

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-config:
          - version: "3.8"
            tox-env: "py38"
          - version: "3.9"
            tox-env: "py39"
          - version: "3.10"
            tox-env: "py310"
          - version: "3.11"
            tox-env: "py311"
          - version: "3.12"
            tox-env: "py312"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for hatch-vcs to work
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python ${{ matrix.python-config.version }}
        run: uv python install ${{ matrix.python-config.version }}
      - name: Configure git for tests
        run: git config --global protocol.file.allow always
      - name: Run tests with tox
        run: uvx --with tox-uv tox -e ${{ matrix.python-config.tox-env }}
